import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Clear existing data
  await prisma.car.deleteMany()
  await prisma.review.deleteMany()
  await prisma.stats.deleteMany()
  await prisma.article.deleteMany()
  await prisma.contactRequest.deleteMany()

  // CARS
  const cars = [
    {
      slug: 'hyundai-sonata-2020',
      brand: 'Hyundai',
      model: 'Sonata',
      title: 'Hyundai Sonata 2.0 Intelligent 2020',
      category: 'standard',
      price: 2150000,
      year: 2020,
      mileage: 68400,
      engineType: 'Бензин',
      engineVolume: '1999 см³',
      horsepower: 163,
      transmission: 'АКПП',
      drive: '2WD (передний)',
      bodyType: 'Седан',
      seats: 5,
      configuration: '2.0 Intelligent',
      shortDescription: 'Популярный корейский седан бизнес-класса с богатой комплектацией. Отличный выбор для городских поездок и трасс. Ухоженное состояние, один владелец, полная история обслуживания.',
      fullDescription: 'Hyundai Sonata 8 поколения — один из самых продаваемых автомобилей Кореи. Автомобиль находится в отличном техническом и внешнем состоянии. Комплектация Intelligent включает: панорамную крышу, вентиляцию и подогрев сидений, систему бесключевого доступа, цифровую приборную панель, Apple CarPlay и Android Auto, камеру 360°, адаптивный круиз-контроль.\n\nАвтомобиль прошёл полную проверку по корейской базе данных CarHistory. Без ДТП, без скрутки пробега. Один владелец с момента покупки. Все технические обслуживания выполнялись в официальных дилерских центрах Hyundai.',
      mainImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
        'https://images.unsplash.com/photo-1580414057403-c5f451f30e1c?w=800&q=80',
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['kia-k5-2021', 'genesis-g70-2020', 'hyundai-grandeur-2019']),
    },
    {
      slug: 'kia-k5-2021',
      brand: 'Kia',
      model: 'K5',
      title: 'Kia K5 2.0 Prestige 2021',
      category: 'standard',
      price: 2450000,
      year: 2021,
      mileage: 45200,
      engineType: 'Бензин',
      engineVolume: '1999 см³',
      horsepower: 150,
      transmission: 'АКПП',
      drive: '2WD (передний)',
      bodyType: 'Седан',
      seats: 5,
      configuration: '2.0 Prestige',
      shortDescription: 'Стильный флагман Kia с дизайном от Питера Шрайера. Богатая комплектация Prestige, низкий пробег, идеальное техническое состояние. Один из самых красивых корейских седанов.',
      fullDescription: 'Kia K5 третьего поколения — принципиально новый автомобиль с агрессивной внешностью и продвинутыми технологиями. Комплектация Prestige включает: проекционный дисплей HUD, матричные светодиодные фары, систему ночного видения, Bose Premium Audio, массаж передних сидений, 10.25" мультимедийный экран.\n\nАвтомобиль без истории ДТП, чистая история по базе CarHistory Корея. Пробег 45 200 км полностью подтверждён. Техническое обслуживание в официальных сервисах Kia.',
      mainImage: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
        'https://images.unsplash.com/photo-1609752631953-47c73e80b9a7?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['hyundai-sonata-2020', 'genesis-g70-2020']),
    },
    {
      slug: 'genesis-g70-2020',
      brand: 'Genesis',
      model: 'G70',
      title: 'Genesis G70 3.3T Sport AWD 2020',
      category: 'business',
      price: 3950000,
      year: 2020,
      mileage: 38700,
      engineType: 'Бензин Турбо',
      engineVolume: '3342 см³',
      horsepower: 370,
      transmission: 'АКПП 8-ступ.',
      drive: 'AWD (полный)',
      bodyType: 'Седан',
      seats: 5,
      configuration: '3.3T Sport AWD',
      shortDescription: 'Флагман премиального бренда Genesis — спортивный седан с 370-сильным V6. Полный привод, спортивный пакет Prestige. Конкурент BMW 3 серии и Mercedes C-Class из Кореи.',
      fullDescription: 'Genesis G70 — самый спортивный автомобиль премиум-бренда Genesis. Разгон 0-100 км/ч за 4.7 секунды благодаря 370-сильному битурбо V6. Полный привод, адаптивные амортизаторы Sachs, спортивный тормозной комплекс Brembo.\n\nКомплектация Sport AWD Prestige: кожа Nappa, 19" кованые диски, адаптивные полноматричные LED фары, обогрев и вентиляция всех сидений, Lexicon Premium Audio, дисплей HUD, система распознавания разметки и пешеходов.',
      mainImage: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
        'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['genesis-gv80-2021', 'kia-stinger-2020', 'hyundai-sonata-2020']),
    },
    {
      slug: 'genesis-gv80-2021',
      brand: 'Genesis',
      model: 'GV80',
      title: 'Genesis GV80 3.5T AWD 2021',
      category: 'premium',
      price: 5800000,
      year: 2021,
      mileage: 29100,
      engineType: 'Бензин Турбо',
      engineVolume: '3470 см³',
      horsepower: 380,
      transmission: 'АКПП 8-ступ.',
      drive: 'AWD (полный)',
      bodyType: 'Внедорожник',
      seats: 7,
      configuration: '3.5T AWD Prestige',
      shortDescription: 'Флагманский внедорожник Genesis — корейский ответ Range Rover и BMW X7. Полноразмерный 7-местный SUV с роскошным интерьером, 380 л.с. и полным перечнем опций.',
      fullDescription: 'Genesis GV80 — первый полноразмерный внедорожник люксового бренда Genesis. Пространство в салоне класса Range Rover, технологии уровня Lexus LS.\n\nКомплектация 3.5T AWD Prestige: панорамная крыша с электроуправлением, массаж 5 зон для водителя, 21" кованые диски, Lexicon 17-speaker Premium Audio, камера 3D 360° с ночным видением, система автоматического движения по полосе, распознавание дорожных знаков, HUD дисплей 10".',
      mainImage: 'https://images.unsplash.com/photo-1571987502227-9231b837d92a?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1571987502227-9231b837d92a?w=800&q=80',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['genesis-g70-2020', 'kia-sorento-2022']),
    },
    {
      slug: 'kia-sportage-2022',
      brand: 'Kia',
      model: 'Sportage',
      title: 'Kia Sportage 2.0 Prestige 2022',
      category: 'comfort',
      price: 1980000,
      year: 2022,
      mileage: 22800,
      engineType: 'Бензин',
      engineVolume: '1999 см³',
      horsepower: 150,
      transmission: 'АКПП',
      drive: '2WD (передний)',
      bodyType: 'Кроссовер',
      seats: 5,
      configuration: '2.0 Prestige',
      shortDescription: 'Свежий Kia Sportage 5-го поколения с новым дизайном «звёздная карта». Отличный выбор для семьи — просторный, экономичный, надёжный. Идеальное техническое состояние.',
      fullDescription: 'Kia Sportage пятого поколения полностью переработан: новый двигатель, новая платформа, революционный интерьер с изогнутым двойным экраном. Один из самых популярных кроссоверов в Корее 2022 года.\n\nКомплектация Prestige: двойной изогнутый дисплей 12.3"+12.3", беспроводной CarPlay/Android Auto, подогрев рулевого колеса, вентиляция передних сидений, панорамная крыша, Smart Cruise Control, Lane Keeping Assist.',
      mainImage: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['hyundai-tucson-2022', 'kia-sorento-2022']),
    },
    {
      slug: 'hyundai-tucson-2022',
      brand: 'Hyundai',
      model: 'Tucson',
      title: 'Hyundai Tucson 1.6T Hybrid 2022',
      category: 'comfort',
      price: 2280000,
      year: 2022,
      mileage: 31600,
      engineType: 'Гибрид',
      engineVolume: '1598 см³',
      horsepower: 230,
      transmission: 'АКПП 6-ступ.',
      drive: 'AWD (полный)',
      bodyType: 'Кроссовер',
      seats: 5,
      configuration: '1.6T Hybrid AWD',
      shortDescription: 'Hyundai Tucson 4-го поколения в гибридном исполнении. Экономичный, мощный, с полным приводом. Расход топлива — от 5.8 л/100 км в смешанном цикле. Выгодное сочетание цены и возможностей.',
      fullDescription: 'Hyundai Tucson четвёртого поколения гибридной версии — оптимальный выбор по соотношению цены, экономичности и возможностей. Система HTRAC AWD обеспечивает полный привод, гибридный синергетический привод даёт мощность 230 л.с. при минимальном расходе топлива.\n\nКомплектация Premium: 10.25" навигационный экран, Bose Premium Audio, кожаный салон, панорамная крыша с регулировкой прозрачности, система ночного видения с тепловизором, 19" алюминиевые диски.',
      mainImage: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['kia-sportage-2022', 'kia-sorento-2022']),
    },
    {
      slug: 'kia-stinger-2020',
      brand: 'Kia',
      model: 'Stinger',
      title: 'Kia Stinger 3.3T AWD GT 2020',
      category: 'business',
      price: 3650000,
      year: 2020,
      mileage: 52100,
      engineType: 'Бензин Турбо',
      engineVolume: '3342 см³',
      horsepower: 370,
      transmission: 'АКПП 8-ступ.',
      drive: 'AWD (полный)',
      bodyType: 'Лифтбек',
      seats: 5,
      configuration: '3.3T GT AWD',
      shortDescription: 'Спортивный лифтбек с 370-сильным V6. Kia Stinger GT — один из немногих доступных спортивных автомобилей из Кореи. Разгон 0-100 за 4.9 секунды. Отличный выбор для любителей динамики.',
      fullDescription: 'Kia Stinger GT — уникальный автомобиль в линейке Kia. Заднеприводная платформа, битурбо V6 мощностью 370 л.с., Brembo тормозная система, адаптивная подвеска Electronic Controlled Suspension.\n\nКомплектация GT: кожа Nappa, 19" кованые диски Brembo, Harman Kardon Premium Audio 720W, спортивные сиденья с боковой поддержкой, проекционный HUD, система контроля давления в шинах на каждое колесо.',
      mainImage: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['genesis-g70-2020', 'kia-k5-2021']),
    },
    {
      slug: 'hyundai-grandeur-2019',
      brand: 'Hyundai',
      model: 'Grandeur',
      title: 'Hyundai Grandeur 3.0 Prestige 2019',
      category: 'business',
      price: 2850000,
      year: 2019,
      mileage: 82120,
      engineType: 'Бензин',
      engineVolume: '2999 см³',
      horsepower: 266,
      transmission: 'АКПП 8-ступ.',
      drive: '2WD (передний)',
      bodyType: 'Седан',
      seats: 5,
      configuration: '3.0 Prestige',
      shortDescription: 'Представительский седан Hyundai для руководителей. Просторный и тихий салон, богатая комплектация Prestige с массажными сиденьями. Один из самых уважаемых автомобилей Кореи.',
      fullDescription: 'Hyundai Grandeur — флагманский седан бренда Hyundai, символ статуса в корейском обществе. Самый тихий и просторный автомобиль в линейке. Атмосферный 3-литровый V6 обеспечивает плавный и тяговитый разгон.\n\nКомплектация Prestige: кожа премиум-класса, массаж водительского сиденья на 8 точках, пневматическая подвеска, Lexicon Premium Audio, цифровая приборная панель 12.3", система очистки воздуха в салоне, охлаждение перчаточного ящика.',
      mainImage: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['genesis-g70-2020', 'hyundai-sonata-2020']),
    },
    {
      slug: 'kia-sorento-2022',
      brand: 'Kia',
      model: 'Sorento',
      title: 'Kia Sorento 2.2D AWD Prestige 2022',
      category: 'comfort',
      price: 3150000,
      year: 2022,
      mileage: 18900,
      engineType: 'Дизель',
      engineVolume: '2199 см³',
      horsepower: 202,
      transmission: 'АКПП 8-ступ.',
      drive: 'AWD (полный)',
      bodyType: 'Внедорожник',
      seats: 7,
      configuration: '2.2 CRDi AWD Prestige',
      shortDescription: 'Семиместный кроссовер с дизельным двигателем и полным приводом. Экономичный расход 7.2 л/100 км, огромный багажник, продвинутая системы безопасности. Идеальный семейный автомобиль.',
      fullDescription: 'Kia Sorento четвёртого поколения — совершенно новая платформа, новый дизайн и передовые технологии. Дизельный двигатель 2.2 CRDi с экономичным расходом топлива отлично подходит для дальних поездок.\n\nКомплектация Prestige 7-мест: третий ряд сидений, полностью кожаный салон, двойной изогнутый дисплей 12.3"+12.3", Harman Kardon Audio 630W, панорамная крыша, камера 360° с просмотром под автомобилем, система помощи при выезде задним ходом, Night Vision.',
      mainImage: 'https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['kia-sportage-2022', 'hyundai-tucson-2022', 'genesis-gv80-2021']),
    },
    {
      slug: 'genesis-g90-2020',
      brand: 'Genesis',
      model: 'G90',
      title: 'Genesis G90 3.3T AWD 2020',
      category: 'premium',
      price: 6200000,
      year: 2020,
      mileage: 41300,
      engineType: 'Бензин Турбо',
      engineVolume: '3342 см³',
      horsepower: 370,
      transmission: 'АКПП 8-ступ.',
      drive: 'AWD (полный)',
      bodyType: 'Седан',
      seats: 5,
      configuration: '3.3T AWD Prestige',
      shortDescription: 'Флагманский седан Genesis — корейский конкурент Mercedes S-Class и BMW 7. Роскошный интерьер с отделкой Nappa, задний ряд бизнес-класса, полный перечень опций. Машина для первых лиц.',
      fullDescription: 'Genesis G90 — вершина линейки Genesis и показатель того, насколько далеко продвинулась корейская автомобильная промышленность. По комфорту задних пассажиров конкурирует с Mercedes S-Class при значительно меньшей цене.\n\nКомплектация Prestige: кожа Nappa высшего сорта, массаж 12 точек для задних пассажиров с режимом «шиацу», панорамная крыша в 3 секции, Lexicon 22-speaker Premium Audio, задние сиденья с режимом First Class с выдвижной подставкой для ног, встроенный холодильник, цифровой ключ, система Preview Electronic Control Suspension.',
      mainImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80',
      galleryImages: JSON.stringify([
        'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80',
      ]),
      damageImages: JSON.stringify([]),
      insuranceImages: JSON.stringify([]),
      damageText: null,
      status: 'active',
      similarCars: JSON.stringify(['genesis-gv80-2021', 'genesis-g70-2020']),
    },
  ]

  for (const car of cars) {
    await prisma.car.create({ data: car })
  }

  // REVIEWS
  const reviews = [
    {
      author: 'Дмитрий К.',
      city: 'Москва',
      rating: 5,
      text: 'Взял Hyundai Sonata через АзияБазар. Ребята всё сделали профессионально: подобрали три варианта, сняли видеообзор каждого, помогли с договором. Автомобиль пришёл точно в срок, состояние один в один как на видео. Рекомендую!',
      date: '12 марта 2025',
      isActive: true,
    },
    {
      author: 'Алина М.',
      city: 'Новосибирск',
      rating: 5,
      text: 'Заказывала Kia Sportage. Никогда раньше не пригоняла авто из Кореи, боялась обмана. АзияБазар развеяли все страхи — полная прозрачность, договор, видео осмотр прямо с корейского дилера. Очень довольна!',
      date: '28 января 2025',
      isActive: true,
    },
    {
      author: 'Игорь В.',
      city: 'Хабаровск',
      rating: 5,
      text: 'Брал Genesis GV80 для семьи. Ребята помогли с проверкой истории, нашли вариант без ДТП с пробегом как у нас говорят «нулевым». Доставка заняла 3 недели. Всё чётко, никаких накладок.',
      date: '5 февраля 2025',
      isActive: true,
    },
    {
      author: 'Светлана Р.',
      city: 'Владивосток',
      rating: 5,
      text: 'Второй раз заказываю через АзияБазар. Первый раз был Tucson, сейчас Sorento. Сервис только улучшился. Отдельное спасибо менеджеру — отвечал буквально в любое время суток. Всё идеально.',
      date: '19 декабря 2024',
      isActive: true,
    },
    {
      author: 'Антон Ш.',
      city: 'Екатеринбург',
      rating: 4,
      text: 'В целом всё нормально, автомобиль соответствует описанию. Единственное — доставка заняла чуть дольше чем планировалось. Но менеджеры предупредили заранее и компенсировали ожидание. Обращусь снова.',
      date: '3 ноября 2024',
      isActive: true,
    },
    {
      author: 'Марина Т.',
      city: 'Казань',
      rating: 5,
      text: 'Заказала Kia K5 мужу на день рождения. Ребята из АзияБазар помогли с выбором, записали обзор, оформили всё под ключ. Муж в восторге! Машина пришла в идеальном состоянии.',
      date: '15 октября 2024',
      isActive: true,
    },
    {
      author: 'Роман Г.',
      city: 'Красноярск',
      rating: 5,
      text: 'Брал Genesis G70 Sport AWD. Проверили по базе CarHistory — всё чисто. Видеообзор сделали подробно, включая подкапотное пространство и тест-драйв. Очень профессиональный подход. Авто огонь!',
      date: '7 сентября 2024',
      isActive: true,
    },
    {
      author: 'Наталья П.',
      city: 'Иркутск',
      rating: 5,
      text: 'Hyundai Grandeur через АзияБазар — лучшая покупка за последние годы. Цена была на 600 тысяч ниже, чем в России. Сервис на высшем уровне, всё прозрачно и по договору. Спасибо команде!',
      date: '22 августа 2024',
      isActive: true,
    },
  ]

  for (const review of reviews) {
    await prisma.review.create({ data: review })
  }

  // STATS
  await prisma.stats.create({
    data: {
      id: 'main',
      selectedCars: 847,
      deliveredCars: 624,
      completedDeals: 598,
      happyClients: 581,
    },
  })

  // ARTICLE
  await prisma.article.create({
    data: {
      slug: 'kakie-avto-vygodno-prignat',
      title: 'Какие автомобили выгодно пригнать из Кореи',
      excerpt: 'Разбираем 4 основные категории автомобилей под разные бюджеты: от доступных городских моделей до представительских седанов. Узнайте, какой автомобиль даст максимальную выгоду именно вам.',
      coverImage: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=80',
      publishedAt: new Date('2025-03-10'),
      content: JSON.stringify({
        intro: 'Корейский автомобильный рынок — один из самых развитых в мире. Производители Hyundai, Kia и Genesis выпускают автомобили, которые по качеству ничем не уступают европейским и японским аналогам, а по цене в России могут быть дешевле на 30–50%. В этой статье мы разберём 4 основные категории автомобилей, которые выгоднее всего пригонять из Кореи.',
        categories: [
          {
            name: 'Комфорт',
            emoji: '🚗',
            description: 'Городские автомобили и компактные кроссоверы корейского рынка. Идеальный старт для тех, кто хочет качественный автомобиль с богатой комплектацией за разумные деньги.',
            whoFor: 'Молодые семьи, городские жители, первая серьёзная машина',
            advantages: ['Низкий расход топлива', 'Богатая базовая комплектация', 'Высокая надёжность', 'Выгодная цена страховки в России'],
            budget: 'от 1 500 000 до 2 500 000 ₽',
            examples: ['Kia Sportage (2020–2023)', 'Hyundai Tucson (2020–2023)', 'Kia Sorento (2020–2022)', 'Hyundai Santa Fe (2019–2021)'],
          },
          {
            name: 'Стандарт',
            emoji: '🚘',
            description: 'Седаны и кроссоверы среднего класса с технологиями, которые в России стоят на 30–40% дороже. Корейские стандартные комплектации часто превосходят европейские бизнес-класс.',
            whoFor: 'Деловые люди, семьи с детьми, те, кто ценит технологии',
            advantages: ['Топовые технологии безопасности', 'Полноценный кожаный салон', 'Панорамные крыши и массаж', 'Отличная шумоизоляция'],
            budget: 'от 2 000 000 до 3 000 000 ₽',
            examples: ['Hyundai Sonata (2019–2022)', 'Kia K5 (2020–2022)', 'Hyundai Grandeur (2018–2021)', 'Kia Stinger (2018–2022)'],
          },
          {
            name: 'Бизнес',
            emoji: '🏎️',
            description: 'Представительские автомобили и спортивные модели Genesis. Уровень оснащения — как у немецких конкурентов, но цена на 40–60% ниже при сопоставимом или лучшем качестве.',
            whoFor: 'Руководители, ценители статуса и динамики, бизнес-класс',
            advantages: ['Спортивная управляемость', 'Статусный внешний вид', 'Максимальные комплектации', 'Высокая остаточная стоимость'],
            budget: 'от 3 000 000 до 5 000 000 ₽',
            examples: ['Genesis G70 3.3T (2019–2021)', 'Genesis G80 3.5T (2020–2022)', 'Kia Stinger GT (2019–2021)', 'Hyundai Grandeur 3.0 (2018–2020)'],
          },
          {
            name: 'Премиум',
            emoji: '👑',
            description: 'Флагманские автомобили Genesis — G90 и GV80. Конкурируют с Mercedes S-Class, BMW 7, Range Rover. Роскошь на уровне $100k+ автомобилей, но с экономией 40–50%.',
            whoFor: 'Топ-менеджеры, предприниматели, ценители настоящей роскоши',
            advantages: ['Уровень Rolls-Royce по комфорту задних пассажиров', 'Эксклюзивный сервис Genesis', 'Максимальная шумоизоляция', 'Полный перечень систем безопасности'],
            budget: 'от 5 000 000 до 8 000 000 ₽',
            examples: ['Genesis G90 3.5T (2019–2022)', 'Genesis GV80 3.5T (2020–2022)', 'Genesis GV70 3.5T (2021–2023)', 'Genesis G80 3.5T Electrified (2021–2022)'],
          },
        ],
        conclusion: 'Какую бы категорию вы ни выбрали — выгода от покупки автомобиля в Корее через АзияБазар очевидна. Мы поможем подобрать оптимальный вариант под ваш бюджет, проверим историю, снимем видеообзор и организуем доставку под ключ.',
      }),
    },
  })

  console.log('✅ Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
